.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

stages:
  - build_docker_images
  - build

build_ubuntu_image:
  only:
    refs:
      - master
    changes:
      - Docker/Ubuntu/*
  stage: build_docker_images
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd Docker/Ubuntu
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/tloe/tengine:ubuntu .
    - docker push registry.gitlab.com/tloe/tengine:ubuntu

# build_windows:
#   extends:
#   - .shared_windows_runners
#   stage: build
#   script:
#   - echo "running scripts in the build job"
#   - cd build
#   - cmake ../
#   - make

build_ubuntu:
  image: registry.gitlab.com/tloe/tengine:ubuntu
  services: 
    - docker:dind
  stage: build
  script:
    - echo "Building in ubuntu image"
    - mkdir build
    - cd build
    - export CC=clang
    - export CXX=clang++
    - conan config install ../remotes.txt 
    - conan install .. -s compiler=clang -s compiler.version=11 -s compiler.libcxx=libc++ --build=missing
    - cmake ../
    - make 
