stages:
  - build_docker_images
  - build

build_ubuntu_image:
  only:
    changes:
      - Utils/Docker/Ubuntu/Dockerfile
  image: docker:latest
  stage: build_docker_images
  # image: registry.gitlab.com/tloe/tengine:ubuntu
  services:
    - docker:dind
  script:
    - cd Utils/Docker/Ubuntu
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/tloe/tengine:ubuntu .
    - docker push registry.gitlab.com/tloe/tengine:ubuntu

build_ubuntu:
  image: registry.gitlab.com/tloe/tengine:ubuntu
  tags:
    - tengine-ubuntu
  services: 
    - docker:dind
  stage: build
  script:
    - mkdir build
    - cd build
    - export CC=clang
    - export CXX=clang++
    - conan config install Utils/Conan/settings.yml
    - conan export ../Utils/Conan/Luajit/luajit.py
    - conan install .. --profile ../Utils/Conan/Profiles/Linux/TEngineRelease -g cmake --build=missing
    - conan build .. 

build_windows:
  tags:
    - tengine-windows
  stage: build
  script:
    - $env:Path += ';C:\Program Files\CMake\bin'
    - $env:Path += ';C:\Users\Terje\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts'
    - mkdir build
    - cd build
    - conan export ..\Utils\Conan\Luajit\luajit.py || true #Ignore exit code 1
    - conan install .. --profile ..\Utils\Conan\Profiles\Msvc\TEngineRelease -g cmake_multi --build=missing
    - conan build ..

